import { MigrationInterface, QueryRunner } from "typeorm";

export class AddOrderCancellationFields1774387429369 implements MigrationInterface {
    name = 'AddOrderCancellationFields1774387429369'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "carts_new_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "product_variants_new_productId_fkey"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "cart_items_new_variantId_fkey"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "cart_items_new_productId_fkey"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "cart_items_new_cartId_fkey"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_new_categoryId_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_new_variantId_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_new_productId_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_new_orderId_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP CONSTRAINT "order_history_new_changedByUserId_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP CONSTRAINT "order_history_new_orderId_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_new_deliveryPlatformId_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_new_customerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_new_assignedToId_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_new_wilayaId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_customers_new_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carts_new_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carts_new_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_variants_new_product"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_variants_new_sku"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_variants_new_composite"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cart_items_new_cart"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cart_items_new_product"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cart_items_new_variant"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_new_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_new_sku"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_new_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_new_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_new_product"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_new_variant"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_history_new_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_history_new_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_history_new_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_new_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_new_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_new_customer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_new_assigned"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_new_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_new_wilaya"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_cancellationstatus_enum" AS ENUM('none', 'requested', 'confirmed')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "cancellationStatus" "public"."orders_cancellationstatus_enum" NOT NULL DEFAULT 'none'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "cancellationReason" text`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "UQ_3e418bff40d3abac5642cd5d398" UNIQUE ("phoneNumber")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "defaultAddress"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "defaultAddress" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "action" "public"."order_history_action_enum" NOT NULL DEFAULT 'Créé'`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "status" "public"."order_history_status_enum"`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" DROP CONSTRAINT "delivery_platforms_new_name_key"`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" ADD CONSTRAINT "UQ_039c70e736c21d586272bd50a96" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deliveryType"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deliveryType" "public"."orders_deliverytype_enum" DEFAULT 'Domicile'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "validationOutcome"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "validationOutcome" "public"."orders_validationoutcome_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" "public"."orders_status_enum" NOT NULL DEFAULT 'En attente'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "source" "public"."orders_source_enum" NOT NULL DEFAULT 'Other'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'customer'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar" character varying(500)`);
        await queryRunner.query(`CREATE INDEX "IDX_3e418bff40d3abac5642cd5d39" ON "customers" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf9a37169945cf32779a304728" ON "carts" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_69828a178f152f157dcf2f70a8" ON "carts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0b921ad4713592268f97b9bab" ON "product_variants" ("productId", "size", "color") `);
        await queryRunner.query(`CREATE INDEX "IDX_46f236f21640f9da218a063a86" ON "product_variants" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_f515690c571a03400a9876600b" ON "product_variants" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a27845bc2d79be6f1fa3d2c03" ON "cart_items" ("variantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_72679d98b31c737937b8932ebe" ON "cart_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_edd714311619a5ad0952504583" ON "cart_items" ("cartId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff39b9ac40872b2de41751eedc" ON "products" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_c44ac33a05b144dd0d9ddcf932" ON "products" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff56834e735fa78a15d0cf2192" ON "products" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_516736b9807228bb17b2d0a3e2" ON "order_items" ("variantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdb99c05982d5191ac8465ac01" ON "order_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0af6da01c049f96d7954888e85" ON "order_history" ("changedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7fc28934aa68c5a269fb4723a" ON "order_history" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_e15b4a73a3e53311433968993c" ON "order_history" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4be52755ec6531d3533238bc2d" ON "orders" ("wilayaId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6044676cec9cebd99349adf41" ON "orders" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_58196933a1c73fc71d2149d39b" ON "orders" ("assignedToId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5de51ca888d8b1f5ac25799dd" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_69828a178f152f157dcf2f70a89" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_72679d98b31c737937b8932ebe6" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_5a27845bc2d79be6f1fa3d2c036" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_516736b9807228bb17b2d0a3e2a" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD CONSTRAINT "FK_e15b4a73a3e53311433968993cc" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD CONSTRAINT "FK_0af6da01c049f96d7954888e85a" FOREIGN KEY ("changedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_4be52755ec6531d3533238bc2de" FOREIGN KEY ("wilayaId") REFERENCES "wilayas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_58196933a1c73fc71d2149d39b6" FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_23fdf30c3994ef48cabdf748d0f" FOREIGN KEY ("deliveryPlatformId") REFERENCES "delivery_platforms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_23fdf30c3994ef48cabdf748d0f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_58196933a1c73fc71d2149d39b6"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_4be52755ec6531d3533238bc2de"`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP CONSTRAINT "FK_0af6da01c049f96d7954888e85a"`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP CONSTRAINT "FK_e15b4a73a3e53311433968993cc"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_516736b9807228bb17b2d0a3e2a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_5a27845bc2d79be6f1fa3d2c036"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_72679d98b31c737937b8932ebe6"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_69828a178f152f157dcf2f70a89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5de51ca888d8b1f5ac25799dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58196933a1c73fc71d2149d39b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6044676cec9cebd99349adf41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4be52755ec6531d3533238bc2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e15b4a73a3e53311433968993c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7fc28934aa68c5a269fb4723a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0af6da01c049f96d7954888e85"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdb99c05982d5191ac8465ac01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_516736b9807228bb17b2d0a3e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff56834e735fa78a15d0cf2192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c44ac33a05b144dd0d9ddcf932"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff39b9ac40872b2de41751eedc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edd714311619a5ad0952504583"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72679d98b31c737937b8932ebe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a27845bc2d79be6f1fa3d2c03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f515690c571a03400a9876600b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46f236f21640f9da218a063a86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0b921ad4713592268f97b9bab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69828a178f152f157dcf2f70a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf9a37169945cf32779a304728"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e418bff40d3abac5642cd5d39"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "source" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "validationOutcome"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "validationOutcome" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deliveryType"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deliveryType" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" DROP CONSTRAINT "UQ_039c70e736c21d586272bd50a96"`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_platforms" ADD CONSTRAINT "delivery_platforms_new_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "status" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "order_history" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD "action" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "defaultAddress"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "defaultAddress" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "UQ_3e418bff40d3abac5642cd5d398"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "cancellationReason"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "cancellationStatus"`);
        await queryRunner.query(`DROP TYPE "public"."orders_cancellationstatus_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_orders_new_wilaya" ON "orders" ("wilayaId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_new_phone" ON "orders" ("phoneNumber") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_new_assigned" ON "orders" ("assignedToId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_new_customer" ON "orders" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_new_created" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_new_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_order_history_new_user" ON "order_history" ("changedByUserId") `);
        await queryRunner.query(`CREATE INDEX "idx_order_history_new_timestamp" ON "order_history" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "idx_order_history_new_order" ON "order_history" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_new_variant" ON "order_items" ("variantId") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_new_product" ON "order_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_new_order" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "idx_products_new_active" ON "products" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_products_new_sku" ON "products" ("sku") `);
        await queryRunner.query(`CREATE INDEX "idx_products_new_category" ON "products" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "idx_cart_items_new_variant" ON "cart_items" ("variantId") `);
        await queryRunner.query(`CREATE INDEX "idx_cart_items_new_product" ON "cart_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "idx_cart_items_new_cart" ON "cart_items" ("cartId") `);
        await queryRunner.query(`CREATE INDEX "idx_product_variants_new_composite" ON "product_variants" ("productId", "size", "color") `);
        await queryRunner.query(`CREATE INDEX "idx_product_variants_new_sku" ON "product_variants" ("sku") `);
        await queryRunner.query(`CREATE INDEX "idx_product_variants_new_product" ON "product_variants" ("productId") `);
        await queryRunner.query(`CREATE INDEX "idx_carts_new_active" ON "carts" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_carts_new_user" ON "carts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_customers_new_phone" ON "customers" ("phoneNumber") `);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_new_wilayaId_fkey" FOREIGN KEY ("wilayaId") REFERENCES "wilayas"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_new_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_new_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_new_deliveryPlatformId_fkey" FOREIGN KEY ("deliveryPlatformId") REFERENCES "delivery_platforms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD CONSTRAINT "order_history_new_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_history" ADD CONSTRAINT "order_history_new_changedByUserId_fkey" FOREIGN KEY ("changedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_new_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_new_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_new_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_new_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_new_cartId_fkey" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_new_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_new_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_new_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "carts_new_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
